### ISSUE TITLE
missing .gitattributes

### ISSUE THREAD

**Issue by wgyalpo** [coolOrangeLabs/powerjobs-samples#3]
The .gitattributes is missing is powerjobs-sample repository and therefore the ps1 files are treated as binary files. That means the commit history doesn't do the diff of what was changed in the commits. 
@christiangessner Is that intentional? I believe it is a case of oversight. 
Add .gitattributes to this repository.

**Comment by christiangessner** [comment]
Hi Wangdu, you are right, this is not intentional. Please feel free to change the .gitattributes to solve this issue.
Thanks,
Christian

**Comment by wgyalpo** [comment]
The problem was with the encodings. Saved the ps1 file with UTF-8 encodings and now the GitHub doesn't treat the file as binary anymore.
